## YAML Template.

spring:
    application.name: word
    profiles.active: development
    main:
        web-enviroment: true
        
---

spring:
    profiles: development
    
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost/emprestimodb
        username: root
        password: 123
        
---

spring:
    profiles: test
    
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:test
        username: sa
        password: 